.Dd $Mdocdate$
.Dt SLANT 1
.Os
.Sh NAME
.Nm slant
.Nd client for remote system monitoring
.Sh SYNOPSIS
.Nm slant
.Op Fl o Ar order
.Op Fl w Ar waittime
.Ar url...
.Sh DESCRIPTION
The
.Nm
utility displays system statistics gathered from
.Ar url .
The resource at each
.Ar url
must be running
.Xr slant-cgi 8 .
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl o Ar order
Default order of host listing.
May be
.Ar cmdline
for natural order,
.Ar host
for hostname,
.Ar cpu
for immediate CPU, or
.Ar mdm
for immediate memory.
.It Fl w
Wait time before querying hosts.
This must be at least 15 seconds.
.El
.Pp
By default, hosts are ordered as given on the command line and are
queried every 15 seconds.
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.Sh EXAMPLES
To query the localhost and a remote machine:
.Bd -literal
% slant -o host localhost/cgi-bin/slant-cgi https://remote/slant-cgi
.Ed
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.\" .Sh SEE ALSO
.\" .Xr foobar 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
