.\"	$Id$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SLANT 1
.Os
.Sh NAME
.Nm slant
.Nd client for remote system monitoring
.Sh SYNOPSIS
.Nm slant
.Op Fl f Ar config
.Op Fl o Ar order
.Op Ar url...
.Sh DESCRIPTION
The
.Nm
utility displays system statistics gathered from resources listed in
.Pa ~/.slantrc .
These resource must be running
.Xr slant-cgi 8 .
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl f Ar config
Specify an alternate configuration location.
.It Fl o Ar order
Default order of host listing.
May be
.Ar cmdline
for natural order,
.Ar host
for hostname,
.Ar cpu
for immediate CPU, or
.Ar mem
for immediate memory.
.It Ar url
Override the configuration's hosts with those provided.
See
.Sx URLs
for details.
.El
.Pp
By default, hosts are ordered as given in the configuration and are
queried every 60 seconds.
If hosts are passed as arguments to
.Nm ,
they are used instead of the configuration file's.
.Pp
If not overridden in the configuration, host status is displayed as
if given the following configuration:
.Bd -literal -offset indent
layout {
  header ;
  errlog 10 ;
  host {
    cpu qmin_bars qmin hour ;
    mem qmin_bars qmin hour ;
    nprocs qmin_bars qmin hour ;
    net qmin hour ;
    disc qmin hour ;
    link ip state access ;
    rprocs qmin ;
    host record ;
  } ;
} ;
.Ed
.Pp
.Nm
needs a minimum of about 90 columns to display data, plus more depending
upon the length of the domain names.
If the window isn't wide enough, the following are elided until the
minimum size is reached:
.Pp
.Bl -enum -compact
.It
bar charts
.It
hourly records
.It
link IP and state
.El
.Pp
Data is not recorded to the local machine: it is
.Qq live .
So if the front-end is shut down and restarted with hosts that are
unresponsive, their data will not be refreshed til the next access.
.Pp
An error and debug log is shown below the table of all hosts.
The log is saved to
.Pa ~/.slant-errlog .
.Ss Configuration file
The configuration file, which defaults to
.Pa ~/.slantrc ,
is structured with the following top-level nodes.
All tokens are white-space separated, so
.Qq servers foo;
species a server named
.Qq foo; .
Literals are case sensitive.
.Bd -literal -offset indent
"waittime" NUM ";"
"timeout" NUM ";"
.Ed
.Pp
The global
.Li waittime
before each host is processed.
The countdown for each host begins after its last disconnect.
The minimum is 15 secons.
Also the global
.Li timeout
after which data transfers are terminated (following the last byte
transferred).
The minimum is 10 seconds.
.Bd -literal -offset indent
"servers" url [url...] ["{"
  ["waittime" NUM ";" ]
  ["timeout" NUM ";" ]
"}"] ";"
.Ed
.Pp
There may be several
.Cm servers
sections, each with different server arguments overriding the globals.
See
.Sx URLs
for details on the
.Li url
field.
.Bd -literal -offset indent
"layout" "{"
  ["header" ";"]
  ["host" "{" [column]+ "}" ";"
  ["errlog" NUM ";"]
"}" ";"
.Ed
.Pp
The
.Cm layout
block configures how host are displayed.
If
.Cm header
is specified, a column header is shown at the top of the screen.
If
.Cm errlog
is non-zero, it is the rows in the error/debug window.
The
.Cm host
block consists of a series of column types and arguments.
Each column may have up to six lines of content.
If the column arguments do not have a line specification, they're
assumed to be on the first line.
In the event of duplicate lines, only the last is retained.
A column for a host ends in a semicolon or the close-brace for the host
layout block.
.Bd -literal -offset indent
"host" "{"
 [ coltype
   [ "line1" "{" colargs "}" |
     "line2" "{" colargs "}" |
     "line3" "{" colargs "}" |
     "line4" "{" colargs "}" |
     "line5" "{" colargs "}" |
     "line6" "{" colargs "}" |
     colargs
   ] ";" ]+
"}" ";"]
.Ed
.Pp
The column types and arguments are as follows:
.Bd -literal -offset indent
"cpu" [time_interval_bars|time_interval]+
"mem" [time_interval_bars|time_interval]+
"net" [time_interval]+
"disc" [time_interval]+
"link" ["ip"|"state"|"access"]+
"host" ["record"|"slant_version"|"uptime"|"clock_drift"|uname]+
"nprocs" [time_interval_bars|time_interval]+
"rprocs" [time_interval_bars|time_interval]+
"nfiles" [time_interval_bars|time_interval]+
.Ed
.Pp
The
.Cm time_interval_bars
fields draw coloured bar graph when specifying
.Cm qmin_bars ,
for the quarter-minute summary;
.Cm min_bars ,
the minute summary;
.Cm hour_bars ,
the hourly summary;
.Cm day_bars ,
the daily summary;
.Cm week_bars ,
the weekly summary; and
.Cm year_bars ,
the yearly summary.
The
.Cm time_interval
writes a percentage when specifying
.Cm qmin ,
for the quarter-minute summary;
.Cm min ,
for the minute summary;
.Cm hour ,
for the hourly summary;
.Cm day ,
for the daily summary;
.Cm week ,
for the weekly summary; or
.Cm year ,
for the yearly summary.
These summaries depend upon the category.
.Pp
The
.Cm uname
fields may be
.Cm machine ,
for host hardware;
.Cm osversion ,
for OS-specific version;
.Cm osrelease ,
for OS-specific release; and
.Cm osname ,
for operating system name.
.Bl -tag -width Ds
.It Cm cpu
CPU time averaged across all cores/CPUs on the system.
Summaries are shown as percentages.
Percentages more than 80% are coloured red; more than 50%, yellow.
The bar graph of the instantaneous view coloured in the same way.
.It Cm mem
Memory usage (all active memory over all pages).
Summaries are shown as percentage.
Percentages more than 80% are coloured red; more than 50%, yellow.
The bar graph of the instantaneous view coloured in the same way.
.It Cm net
Data received and transmitted as averaged over all network devices.
Summaries are in human-readable scaled units (e.g., KB/s).
.It Cm disc
Data read and written as averaged over all configured devices.
This is shown as an average over two intervals: in the last 15
Summaries are in human-readable scaled units (e.g., KB/s).
.It Cm link
If requesting
.Cm ip ,
the IP address (IPV4 or IPV6) of the host and the connection state.
If
.Cm state ,
may be one of
.Li strt ,
startup;
.Li rslv ,
resolving;
.Li idle ,
waiting for next connection;
.Li cnrd ,
ready to connect;
.Li cnct ,
connecting;
.Li cldn ,
connection finished (success);
.Li cler ,
connection finished (error);
.Li wrte ,
writing request; or
.Li read ,
reading response.
Lastly,
.Cm access
is the time since last ping.
Shown as hours, minutes, seconds elapsed.
If a worrying amount of elapsed time has shown, the time will be shown
in yellow.
If the amount indicates problems, it will be shown in red.
.It Cm host
If
.Cm record ,
the last data collection time as recorded by the remote host's
collection system.
Shown as hours, minutes, seconds elapsed.
If a worrying amount of elapsed time has shown, the time will be shown
in yellow.
If the amount indicates problems, it will be shown in red.
The last connection time as recorded by the local host's
Shown as hours, minutes, seconds elapsed.
If a worrying amount of elapsed time has shown, the time will be shown
in yellow.
If the amount indicates problems, it will be shown in red.
The
.Cm slant_version ,
column argument prints the collector version.
Lastly,
.Cm uptime
prints the uptime in days, hours, and minutes.
.It Cm nprocs
The number of running processes over the maximum configured amount.
Summaries are in percentages.
Percentages more than 80% are coloured red; more than 50%, yellow.
The bar graph of the instantaneous view is coloured in the same way.
.It Cm rprocs
Of the commands given to the collector for monitoring, the percentage
that are running.
Summaries are in percentages.
If no commands were given, is always 100%.
If less than 100%, shown in red.
.It Cm nfiles
The number of open files over the maximum possible amount.
Summaries are in percentages.
Percentages more than 80% are coloured red; more than 50%, yellow.
The bar graph of the instantaneous view is coloured in the same way.
.El
.Pp
The hostname (domain name) is always shown first.
.Ss URLs
The URLs passed on the command line or in the configuration file are in
the following format:
.Bd -literal
[https://|http://][username:password@]host[:port][/path][?query]
.Ed
.Pp
If the schema is not provided, HTTP is used regardless of the port (if
given).
The username and password should only be used with HTTPS, but this is
not mandated.
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.Sh EXAMPLES
To query the localhost and a remote machine:
.Bd -literal
% slant -o host
.Ed
.Pp
With the following configuration file:
.Bd -literal -offset indent
waittime 60 ;
servers
  https://remote/slant-cgi
  ;
servers
  localhost/cgi-bin/slant-cgi
  { waittime 15 } ;
.Ed
.Pp
This establishes a default wait time of 60 seconds.
This value is used by the remote host.
The local host has its wait time overriden at 15 seconds.
It uses the default node display.
.Pp
The following is optimised for a quick look at memory and CPU usage of
many hosts, so the error log and header are suppressed.
.Bd -literal -offset indent
waittime 60 ;
servers
  https://remote1/slant-cgi
  https://remote2/slant-cgi
  https://remote3/slant-cgi
  ;
servers
  localhost/cgi-bin/slant-cgi
  { waittime 15 } ;
layout {
  host {
    cpu qmin_bars qmin min hour day ;
    mem qmin_bars qmin min hour day ;
    link access ;
  }
} ;
.Ed
.Pp
A more vertical layout for the same is as follows.
This stacks information using the multi-line features.
.Bd -literal -offset indent
layout {
  host {
    cpu
      line1 { qmin_bars qmin }
      line2 { min_bars min }
      line3 { hour_bars hour }
      line4 { day_bars day }
      line5 { week_bars week }
      line6 { year_bars year } ;
    mem
      line1 { qmin_bars qmin }
      line2 { min_bars min }
      line3 { hour_bars hour }
      line4 { day_bars day }
      line5 { week_bars week }
      line6 { year_bars year } ;
    link
      line1 { access state }
      line2 { ip } ;
  }
} ;
.Ed
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr slant-collectd 8
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
