.\"	$Id$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SLANT-COLLECTD 8
.Os
.Sh NAME
.Nm slant-collectd
.Nd daemon to collect system statistics
.Sh SYNOPSIS
.Nm slant-collectd
.Op Fl nv
.Op Fl d Ar discs
.Op Fl f Ar dbfile
.Op Fl p Ar procs
.Sh DESCRIPTION
The
.Nm
utility collects system statistics and records them in
.Ar dbfile ,
which defaults to
.Pa /var/www/data/slant.db .
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl n
Do not open the database: collect data only.
.It Fl v
Print collected data as a table to standard output.
.It Fl d Ar discs
Discs to monitor.
Multiple discs may be separated by a comma.
By default, all discs are monitored.
.It Fl p Ar procs
Processes to monitor.
Multiple processes may be separated by a comma.
Processes should be listed by their executable name, e.g.,
.Ar httpd
instead of
.Ar /usr/sbin/httpd .
.It Fl f Ar dbfile
The SQLite database file.
.El
.Pp
To end collection, kill the process with
.Dv SIGINT
or
.Dv SIGTERM ,
which will gracefully end the collection sequence.
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.Sh EXAMPLES
On a system with software RAID (or software FDE), monitor only the root
disc to prevent bandwidth duplication.
.Bd -literal
# slant-collectd -d sd0
.Ed
.Pp
To additionally monitor CGI and login facilities:
.Bd -literal
# slant-collectd -d sd0 -p slowcgi,httpd,sshd
.Ed
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.\" .Sh SEE ALSO
.\" .Xr foobar 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
